### ISSUE TITLE
Use unique IDs for clip-paths

### ISSUE THREAD

**Issue by danlevings** [cognitedata/griff-react#33]
When you have multiple charts on one page (as per the dashboards feature in opint), it will take the first clip-path ID you make and use it for all of them - specifically the clip path used to clip the lines to make room for the axes. 

Therefore if you want the first chart to have axes, and the rest not too, it leads to the charts below it being clipped the same way the first chart is. (all clip paths use the same ID).

Question: it doesn't seem like we need this clippath? It doesn't seem to be doing anything when deleted @evancharlton @martincognite

**Comment by evancharlton** [comment]
Turns out that we need clipPath. However, we can make it unique -- which I have done in #34

**Comment by danlevings** [comment]
Interesting, what is the clippath used for?

**Comment by evancharlton** [comment]
The lines are drawn to infinity -- if you zoom in without the clip path, it continues under the axes.
